from __future__ import annotations

from typing import Protocol
from uuid import UUID

from paperbrain.domain.events import DomainEvent
from paperbrain.domain.machines import Machine
from paperbrain.domain.materials import MaterialSpec, MaterialSubstitution
from paperbrain.domain.orders import CustomerOrder, OrderLine
from paperbrain.domain.plans import Plan
from paperbrain.domain.reels import Reel, ReelSegment


class ReelRepository(Protocol):
    def get(self, reel_id: UUID) -> Reel: ...

    def get_by_code(self, reel_code: str) -> Reel: ...

    def list_all(self) -> tuple[Reel, ...]: ...

    def save(self, reel: Reel, *, expected_version: int | None = None) -> None: ...


class ReelSegmentRepository(Protocol):
    def list_all(self) -> tuple[ReelSegment, ...]: ...

    def list_for_reel(self, reel_id: UUID) -> tuple[ReelSegment, ...]: ...

    def replace_for_reel(self, reel_id: UUID, segments: tuple[ReelSegment, ...]) -> None: ...


class OrderRepository(Protocol):
    def get(self, order_id: UUID) -> CustomerOrder: ...

    def list_all(self) -> tuple[CustomerOrder, ...]: ...

    def list_lines(self) -> tuple[OrderLine, ...]: ...

    def save(self, order: CustomerOrder, lines: tuple[OrderLine, ...]) -> None: ...


class MachineRepository(Protocol):
    def list_all(self) -> tuple[Machine, ...]: ...

    def save(self, machine: Machine) -> None: ...


class MaterialRepository(Protocol):
    def list_all(self) -> tuple[MaterialSpec, ...]: ...

    def list_substitutions(self) -> tuple[MaterialSubstitution, ...]: ...

    def save(self, material: MaterialSpec) -> None: ...


class EventStore(Protocol):
    def append(self, event: DomainEvent, *, expected_version: int) -> None: ...

    def for_aggregate(self, aggregate_id: UUID) -> tuple[DomainEvent, ...]: ...


class PlanRepository(Protocol):
    def get(self, plan_id: UUID) -> Plan: ...

    def save(self, plan: Plan) -> None: ...

    def list_all(self) -> tuple[Plan, ...]: ...
